USER_NAME_LENGTH = 150
EMAIL_LENGTH = 254
TEXT_LENGTH = 50
TITLE_LENGTH = 255
RECIPE_NAME_LENGTH = 200
NAME_LENGTH = 256
NAME_TAG_LENGTH = 200
NAME_INGREDIENT_LENGTH = 200
COLOR_LENGTH = 7
SLUG_LENGTH = 200
MEASUREMENT_UNIT_LENGTH = 200
MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1
QUANTITY_DIGITS = 6
QUANTITY_DECIMAL_PLACES = 2
PASSWORD_LENGTH = 150

EMAIL_ADDRESS = 'email address'
PASSWORD = 'password'
FIRST_NAME = 'first name'
LAST_NAME = 'last name'
USER = 'user'
USERS = 'users'
TAG = 'tag'
TAGS = 'tags'
TAG_COLOR = 'tag color code'
ERROR_TAG_COLOR = 'Color must be in HEX format'
TAG_SLUG = 'tag slug'
INGREDIENT = 'ingredient'
INGREDIENTS = 'ingredients'
INGREDIENT_MEASUREMENT_UNIT = 'ingredient measurement unit'
ERROR_INGREDIENT_MESSAGE = 'such ingredient already exists'
RECIPE_AUTHOR = 'recipe author'
RECIPE = 'recipe'
RECIPES = 'recipes'
RECIPE_IMAGE = 'recipe image'
RECIPE_DESCRIPTION = 'recipe description'
RECIPE_INGREDIENTS = 'recipe ingredients'
RECIPE_TAGS = 'recipe tags'
RECIPE_COOKING_TIME = 'recipe cooking time in minutes'
ERROR_COOKING_TIME = 'cooking time cannot be less than {} minute'
INGREDIENT_AMOUNT = 'ingredient amount'
ERROR_INGREDIENT_AMOUNT = 'ingredient amount cannot be less than {}'
INGREDIENT_IN_RECIPE = 'ingredient {} already in recipe {}'
ERROR_RECIPE_IN_SHOPPING_CART = 'recipe already in shopping cart'
RECIPE_IN_SHOPPING_CART = '{} in {}\'s shopping cart'
ERROR_RECIPE_IN_FAVORITE = 'recipe already in favorites'
RECIPE_IN_FAVORITE = '{} in {}\'s favorites'
ALREADY_FOLLOW = 'you already follow this author'
FOLLOWS = '{} follows {}'
PUB_DATE = 'publication date'
