# Generated by Django 3.2.3 on 2024-04-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'default_related_name': 'recipes', 'ordering': ('-id',), 'verbose_name': 'recipe', 'verbose_name_plural': 'recipes'},
        ),
    ]
