# Generated by Django 3.2.3 on 2024-04-27 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'default_related_name': 'recipes', 'ordering': ('-pub_date',), 'verbose_name': 'recipe', 'verbose_name_plural': 'recipes'},
        ),
    ]
